### ISSUE TITLE
Apple Silicon ( M1) compatibility 

### ISSUE THREAD

**Issue by alpat59** [koen-aerts/potdroneflightparser#1]
@koen-aerts you did really a great job… thank you for that. I (and maybe also many other people) find your app extremely useful. Do you think it could possible to create a version for M1 Apple computer? Thanks again

**Comment by koen-aerts** [comment]
Thank you for your comments. I am currently working on some updates to the app (including some additional metrics and some minor overall tweaks) and I am planning to include Mac ARM builds in the next release. Probably around late August or early September.

**Comment by alpat59** [comment]
Great! Thank you for you supportAlberto PatriziInviato da iPhoneIl giorno 4 ago 2023, alle ore 08:33, koen-aerts ***@***.***> ha scritto:﻿
Thank you for your comments. I am currently working on some updates to the app (including some additional metrics and some minor overall tweaks) and I am planning to include Mac ARM builds in the next release. Probably around late August or early September.

**Comment by koen-aerts** [comment]
Binary builds for Mac ARM is now included.

**Comment by alpat59** [comment]
Thank you @koen-aerts
