### ISSUE TITLE
Apple Silicon ( M1) version - doesn't open file 

### ISSUE THREAD

**Issue by alpat59** [koen-aerts/potdroneflightparser#2]
Hi @koen-aerts .. I finally gad time to try your last version M1-compatible (0.6.0 alpha) on my Mac Mini M2.
Feedback:
- some issue to open the file .app until I discovered on google an info regarding a command to execute : "**xattr -d com.apple.quarantine** /Applications/extractFlightData.app (or your path)"; after that, the app opened fine
- it still is impossible to open the flight log .zip file extracted by Potensic Pro app. When you select "open file.." nothing happens.
Maybe I'm wrong something .. so your help will be really appreciated.
Thank you in advance and still thanks for your great job.
Best regards

**Comment by koen-aerts** [comment]
Thank you for your feedback. The first issue you mention is nothing specific to this app. This is a general safety feature in MacOS where it warns people about content they download and run from the Internet. The fix is literally what you already figured out and involves removing the Extended Attributes. The second issue you mention, I think I have a general idea of what's going on and I will take a look at it. It's probably some missing dependencies from the bundle. The app may work for some people, and not for others, depending on whether they already have the libraries on their system.

**Comment by alpat59** [comment]
Thank you @koen-aerts . I'll wait for your update and I'll test it to give you a feedback. Great support ...

**Comment by koen-aerts** [comment]
A couple things to try or look at:
1) Run the app from the command line: open extractFlightData.app --stdout outfile.txt --stderr errfile.txt
When the app launches, try and open a log file, which in your case will not work. Then exist the app and see if anything is written out to either one of the log files, "cat outfile.txt" and "cat errfile.txt". If both are empty, then not much to go on, if there is something in there, please share.
2) If you have multiple screens, does the "open file" menu option open a file dialog on the different screen?
3) What version of OS do you have? Binaries have been built on Big Sur 11.3.1, M1 CPU, Python 3.11.4, pyinstaller 5.13.0. Another option may be to install python universal2 on your MacBook and see if the app takes advantage of that. I know that is not ideal but python based apps and libraries can be challenging to run on ARM architectures. I do have it working on my build machine so there must be some dependency that you're missing and that is also not included in the build. I can dig deeper but that will take some time. If you don't want to wait that long you can try some of the things mentioned above. Thanks for your patience!

**Comment by alpat59** [comment]
Hi @koen-aerts . I finally found some time for test you asked me.
1) outfile.txt was empty. Few rows in err file.txt attached hereunder

2023-09-07 23:03:23.244 extractFlightData[29162:3368354] +[CATransaction synchronize] called within transaction
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter/__init__.py", line 1948, in __call__
  File "extractFlightData.py", line 511, in askForFlightFile
  File "extractFlightData.py", line 469, in parseFile
ValueError: invalid literal for int() with base 16: "'\n"

2) I'm not using multiple screens

3) Mac OS version is 13.5.1 (22G90), Chip is Apple M2 (Mac Mini)

Again thank you for your support.

**Comment by koen-aerts** [comment]
Thanks for providing this log file, that has been extremely helpful as it indicates it could be a bug in the code itself, and not a platform issue - which in a way is good news. You could try to delete the file(s) ending in "-FPV.bin" from the zip file and then open the zip file again in the tool. Make sure your zip filename does not change and no other files or directories end up inside of the zip file.
unzip "20230723-Atom SE-Drone.zip"
rm *-FPV.bin
rm "20230723-Atom SE-Drone.zip"
zip -9ry "20230723-Atom SE-Drone.zip" *.bin
I also wouldn't mind having a copy of your zip file to see if I can reproduce the problem on my end so I can fix it. Follow the link under the "more info" section on this project's main page, this will bring you to my website from where you can reach out to me with your email. After that you can email the file to me directly.

**Comment by alpat59** [comment]
Hi @koen-aerts .. sorry for late answer.. Yes I confirm that deleting he FPV.bin file, your app works well!
Anyway if you still need my zip fil, I can send you.
Let me know.
Thank you

**Comment by koen-aerts** [comment]
Thanks for confirming. Please do send your original zip file as I want to make sure I can build a fix for it in the app.

**Comment by koen-aerts** [comment]
Requested log file not received. A "best effort" fix has been implemented.

**Comment by alpat59** [comment]
Hi @koen-aerts . The fix seems to work well. I loaded the regular zip log file and the ap worked without problem. Anyway I wrote you by website "post a comment" section. So pls, let me know how I can send you the zip file (sorry for delay.. I forgot to do it ...).
Thank you

**Comment by koen-aerts** [comment]
Log file was provided. There are minor differences between the FPV files depending on which mobile platform the Potensic App was running on: Android or iOS. The iOS format of the FPV file will be supported in the next minor release.
