### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by rdrolis** [koen-aerts/potdroneflightparser#3]
Greetings,

I keep getting an index error when opening a log zip file. I am running from the command line so I am including the traceback below. This happens on any zip file I open. IF you have any hints or tips, I would appreciate it. (I can provide a zip file if needed.)

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.11/3.11.7_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/tkinter/__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "/Users/xxxxxx/src/potdroneflightparser/extractFlightData.py", line 928, in askForFlightFile
    self.parseFile(selectedZipfile)
  File "/Users/xxxxxx/src/potdroneflightparser/extractFlightData.py", line 548, in parseFile
    self.parseAtomLogs(droneModel, selectedFile)
  File "/Users/xxxxxx/src/potdroneflightparser/extractFlightData.py", line 603, in parseAtomLogs
    filenameTs = timestampMarkers[0]
                 ~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```

**Comment by koen-aerts** [comment]
Hi, thank you for this feedback. If you can send me a zip file I can take a look at this. If you could leave a comment at the following link I can respond to you via email for the log file: https://koenaerts.ca/micro-drones/parsing-potensic-flight-data-files/

**Comment by rdrolis** [comment]
Comment left on the website.

**Comment by rdrolis** [comment]
There was a recent app update and aircraft firmware update so the file name change maybe due to that. I was able to do a quite a bit of flying yesterday. I am attaching that log file. Maybe it will give you a better picture.



Ray Rolison
***@***.***


On Feb 2, 2024, at 9:02 AM, koen-aerts ***@***.***> wrote:

﻿

The 3 log files you sent each have different problems. One is simply an empty zip file. The other contains the proper files but for some reason the "FC" files have the ".fc" extension instead of the expected ".bin". Never seen that before. Did you rename them or is this a change from the Potensic software? And finally the last file required a fix in the Viewer, which has been updated accordingly.

**Comment by koen-aerts** [comment]
A fix for the filename change has been pushed. It is now included in the source code and will be part of the next release, whichever will come after v1.3.1.

**Comment by rdrolis** [comment]
It seems to be working.  I have tried several files and they work.

**Comment by koen-aerts** [comment]
Marking as resolved. Fixes will be included in the next release build.
